#!/usr/bin/env bash

case "${1}" in
  init)
    while (( "$#" )); do
      case "${2}" in
        --channel=*) CHANNEL=${2/--channel=/''} ; shift ;;
        --emoji=*) EMOJI=${2/--emoji=/''} ; shift ;;
        --silent) SILENT='0' ; shift ;;
        --username=*) USERNAME=${2/--username=/''} ; shift ;;
        --webhook=*) WEBHOOK=${2/--webhook=/''} ; shift ;;
        -c*) CHANNEL=${3} ; shift ; shift ;;
        -e*) EMOJI=${3} ; shift ; shift ;;
        -s) SILENT='0' ; shift ;;
        -u*) USERNAME=${3} ; shift ; shift ;;
        -w*) WEBHOOK=${3} ; shift ; shift ;;
        *) shift ;;
      esac
    done

    test -z "${WEBHOOK}" && read -e -p 'Enter webhook (e.g. https://hooks.slack.com/services/XXX/XXX/XXX): ' WEBHOOK
    test -z "${USERNAME}" && read -e -p 'Enter username (e.g. username-bot): ' USERNAME
    test -z "${EMOJI}" && read -e -p 'Enter emoji (e.g. :robot_face:): ' EMOJI
    test -z "${CHANNEL}" && read -e -p 'Enter default channel (e.g. #general): ' CHANNEL
    test -z "${SILENT}" && echo -n 'Initializing: '

    echo "${WEBHOOK}" > ~/.slack-cli && \
    echo "${CHANNEL}" >> ~/.slack-cli && \
    echo "${USERNAME}" >> ~/.slack-cli && \
    echo "${EMOJI}" >> ~/.slack-cli

    case "$?" in
      0) test -z "${SILENT}" && echo 'done' ; exit 0 ;;
      *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
    esac
  ;;

  send)
    CHANNEL=$(sed -n '2p' < ~/.slack-cli)
    EMOJI=$(sed -n '4p' < ~/.slack-cli)
    USERNAME=$(sed -n '3p' < ~/.slack-cli)
    WEBHOOK=$(sed -n '1p' < ~/.slack-cli)

    while (( "$#" )); do
      case "${2}" in
        --channel=*) CHANNEL=${2/--channel=/''} ; shift ;;
        --silent) SILENT='0' ; shift ;;
        --text=*) TEXT=${2/--text=/''} ; shift ;;
        -c*) CHANNEL=${3} ; shift ; shift ;;
        -s) SILENT='0' ; shift ;;
        -t*) TEXT=${3} ; shift ; shift ;;
        *) test -n "${2}" && TEXT=${2} ; shift ;;
      esac
    done

    test -z "${CHANNEL}" && read -e -p 'Enter channel (e.g. #general): ' CHANNEL
    test -z "${TEXT}" && read -e -p 'Enter text (e.g. Hello World!): ' TEXT
    test -z "${SILENT}" && echo -n 'Sending: '

    PAYLOAD="payload={\"text\": \"${TEXT}\", \"channel\": \"${CHANNEL}\", \"username\": \"${USERNAME}\", \"icon_emoji\": \"${EMOJI}\"}"
    curl --silent --fail -X POST --data-urlencode "${PAYLOAD}" ${WEBHOOK} > /dev/null

    case "$?" in
      0) test -z "${SILENT}" && echo 'done' ; exit 0 ;;
      *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
    esac
  ;;

  sendtmpl)
    CHANNEL=$(sed -n '2p' < ~/.slack-cli)
    EMOJI=$(sed -n '4p' < ~/.slack-cli)
    USERNAME=$(sed -n '3p' < ~/.slack-cli)
    WEBHOOK=$(sed -n '1p' < ~/.slack-cli)

    case "${2}" in
      event)
        COLOR='good'

        while (( "$#" )); do
          case "${3}" in
            --channel=*) CHANNEL=${3/--channel=/''} ; shift ;;
            --color=*) COLOR=${3/--color=/''} ; shift ;;
            --details=*) DETAILS=${3/--details=/''} ; shift ;;
            --event=*) EVENT=${3/--event=/''} ; shift ;;
            --link=*) LINK=${3/--link=/''} ; shift ;;
            --silent) SILENT='0' ; shift ;;
            --title=*) TITLE=${3/--title=/''} ; shift ;;
            -c*) CHANNEL=${4} ; shift ; shift ;;
            -s) SILENT='0' ; shift ;;
            *) shift ;;
          esac
        done

        test -z "${CHANNEL}" && read -e -p 'Enter channel (e.g. #general): ' CHANNEL
        test -z "${EVENT}" && read -e -p 'Enter event (e.g. New version of slack-cli released): ' EVENT
        test -z "${TITLE}" && read -e -p 'Enter title (e.g. v0.2.0): ' TITLE
        test -z "${LINK}" && read -e -p 'Enter link (e.g https://github.com/rockymadden/slack-cli/releases/tag/v0.2.0): ' LINK
        test -z "${DETAILS}" && read -e -p 'Enter details (e.g Introduces new templated messages): ' DETAILS
        test -z "${COLOR}" && read -e -p 'Enter color (e.g. good, warning, danger): ' COLOR
        test -z "${SILENT}" && echo -n 'Sending: '

        PAYLOAD="payload={\"attachments\": [{\"fallback\": \"${EVENT}\", \"pretext\": \"${EVENT}\", \"color\": \"${COLOR}\", \"title\": \"${TITLE}\", \"title_link\": \"${LINK}\", \"text\": \"${DETAILS}\"}], \"channel\": \"${CHANNEL}\", \"username\": \"${USERNAME}\", \"icon_emoji\": \"${EMOJI}\"}"
        curl --silent --fail -X POST --data-urlencode "${PAYLOAD}" ${WEBHOOK} > /dev/null

        case "$?" in
          0) test -z "${SILENT}" && echo 'done' ; exit 0 ;;
          *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
        esac
      ;;

      task)
        COLOR='good'

        while (( "$#" )); do
          case "${3}" in
            --channel=*) CHANNEL=${3/--channel=/''} ; shift ;;
            --color=*) COLOR=${3/--color=/''} ; shift ;;
            --silent) SILENT='0' ; shift ;;
            --what=*) WHAT=${3/--what=/''} ; shift ;;
            --when=*) WHEN=${3/--when=/''} ; shift ;;
            --why=*) WHY=${3/--why=/''} ; shift ;;
            -c*) CHANNEL=${4} ; shift ; shift ;;
            -s) SILENT='0' ; shift ;;
            *) shift ;;
          esac
        done

        test -z "${CHANNEL}" && read -e -p 'Enter channel (e.g. #general): ' CHANNEL
        test -z "${WHAT}" && read -e -p 'Enter what (e.g. Restarting server): ' WHAT
        test -z "${WHY}" && read -e -p 'Enter why (e.g. Out of memory): ' WHY
        test -z "${WHEN}" && read -e -p 'Enter when (e.g. 15:45, Now): ' WHEN
        test -z "${COLOR}" && read -e -p 'Enter color (e.g. good, warning, danger): ' COLOR
        test -z "${SILENT}" && echo -n 'Sending: '

        PAYLOAD="payload={\"attachments\": [{\"author_name\": \"Task Notification\", \"author_icon\": \"http://www.emoji-cheat-sheet.com/graphics/emojis/nut_and_bolt.png\", \"fallback\": \"${WHAT}\", \"text\": \"${WHAT}\", \"color\": \"${COLOR}\", \"fields\": [{\"title\": \"Why\", \"value\": \"${WHY}\", \"short\": true}, {\"title\": \"When\", \"value\": \"${WHEN}\", \"short\": true}]}], \"channel\": \"${CHANNEL}\", \"username\": \"${USERNAME}\", \"icon_emoji\": \"${EMOJI}\"}"
        curl --silent --fail -X POST --data-urlencode "${PAYLOAD}" ${WEBHOOK} > /dev/null

        case "$?" in
          0) test -z "${SILENT}" && echo 'done' ; exit 0 ;;
          *) test -z "${SILENT}" && echo 'fail' ; exit 1 ;;
        esac
      ;;

      *) ${0} --help && exit 1 ;;
    esac
  ;;

  --help)
    a=(${0//\// })
    bin=${a[${#a[@]}-1]}

    echo 'Usage:'
    echo "  ${bin} init [--webhook|-w <webhook>] [--username|-u <username>] [--emoji|-e <emoji>] [--channel|-c <channel>] [--silent|-s]"
    echo "  ${bin} send [--channel|-c <channel>] [--text|-t <text>]  [--silent|-s]"
    echo "  ${bin} sendtmpl event [--channel|-c <channel>] [--event=<event>] [--title=<title>] [--link=<link>] [--details=<details>] [--color=<color>] [--silent|-s]"
    echo "  ${bin} sendtmpl task [--channel|-c <channel>] [--what=<what>] [--why=<why>] [--when=<when>] [--color=<color>] [--silent|-s]"
    echo
    echo "Settings Commands:"
    echo "  init     Initialize default settings"
    echo
    echo "Messaging Commands:"
    echo "  send               Send a message"
    echo "  sendtmpl event     Send an event templated message"
    echo "  sendtmpl task      Send a task notification templated message"
  ;;

  --version) echo 'v0.2.0' ;;

  *) ${0} --help && exit 1 ;;
esac

exit 0
